"""create_initial_core_tables

Revision ID: 07044488077b
Revises: 
Create Date: 2026-10-06 20:51:58.018499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07044488077b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('buyer_type', sa.Enum('WHOLESALER', 'RETAILER', 'PROCESSOR', 'RESTAURANT', 'INSTITUTION', 'OTHER', name='buyer_type_enum', native_enum=False), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyers_district'), 'buyers', ['district'], unique=False)
    op.create_index(op.f('ix_buyers_id'), 'buyers', ['id'], unique=False)
    op.create_table('commodities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('default_unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_code'), 'commodities', ['code'], unique=True)
    op.create_index(op.f('ix_commodities_id'), 'commodities', ['id'], unique=False)
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_district'), 'markets', ['district'], unique=False)
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('identifier', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('FARMER', 'COLD_STORE_OPERATOR', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_identifier'), 'users', ['identifier'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('buyer_demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('required_from', sa.Date(), nullable=False),
    sa.Column('required_until', sa.Date(), nullable=False),
    sa.Column('quality_grade', sa.String(length=20), nullable=False),
    sa.Column('max_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FULFILLED', 'EXPIRED', 'CANCELLED', name='demand_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('max_price_per_kg >= 0', name='chk_buyer_demand_price_non_negative'),
    sa.CheckConstraint('quantity_kg > 0', name='chk_buyer_demand_quantity_positive'),
    sa.CheckConstraint('required_until >= required_from', name='chk_buyer_demand_date_window'),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buyer_demand_commodity_dates', 'buyer_demand', ['commodity_id', 'required_from', 'required_until'], unique=False)
    op.create_index(op.f('ix_buyer_demand_buyer_id'), 'buyer_demand', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_buyer_demand_commodity_id'), 'buyer_demand', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_buyer_demand_id'), 'buyer_demand', ['id'], unique=False)
    op.create_index(op.f('ix_buyer_demand_required_from'), 'buyer_demand', ['required_from'], unique=False)
    op.create_index(op.f('ix_buyer_demand_required_until'), 'buyer_demand', ['required_until'], unique=False)
    op.create_table('cold_store_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_cold_store_operators_id'), 'cold_store_operators', ['id'], unique=False)
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_farmers_district'), 'farmers', ['district'], unique=False)
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_table('market_arrivals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_kg >= 0', name='chk_market_arrival_quantity_non_negative'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'commodity_id', 'date', name='uq_market_commodity_date_arrival')
    )
    op.create_index('idx_market_arrival_lookup', 'market_arrivals', ['commodity_id', 'market_id', 'date'], unique=False)
    op.create_index(op.f('ix_market_arrivals_commodity_id'), 'market_arrivals', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_market_arrivals_date'), 'market_arrivals', ['date'], unique=False)
    op.create_index(op.f('ix_market_arrivals_id'), 'market_arrivals', ['id'], unique=False)
    op.create_index(op.f('ix_market_arrivals_market_id'), 'market_arrivals', ['market_id'], unique=False)
    op.create_table('market_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('min_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('modal_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price_per_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('max_price_per_kg >= modal_price_per_kg', name='chk_market_price_max_gte_modal'),
    sa.CheckConstraint('min_price_per_kg >= 0', name='chk_market_price_min_non_negative'),
    sa.CheckConstraint('modal_price_per_kg >= min_price_per_kg', name='chk_market_price_modal_gte_min'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'commodity_id', 'date', name='uq_market_commodity_date_price')
    )
    op.create_index('idx_market_price_lookup', 'market_prices', ['commodity_id', 'market_id', 'date'], unique=False)
    op.create_index(op.f('ix_market_prices_commodity_id'), 'market_prices', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_market_prices_date'), 'market_prices', ['date'], unique=False)
    op.create_index(op.f('ix_market_prices_id'), 'market_prices', ['id'], unique=False)
    op.create_index(op.f('ix_market_prices_market_id'), 'market_prices', ['market_id'], unique=False)
    op.create_table('cold_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('capacity_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('capacity_kg > 0', name='chk_cold_store_capacity_positive'),
    sa.ForeignKeyConstraint(['operator_id'], ['cold_store_operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cold_stores_district'), 'cold_stores', ['district'], unique=False)
    op.create_index(op.f('ix_cold_stores_id'), 'cold_stores', ['id'], unique=False)
    op.create_index(op.f('ix_cold_stores_operator_id'), 'cold_stores', ['operator_id'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('area_acres', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('irrigation_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_farmer_id'), 'farms', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_table('cold_store_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cold_store_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('LOADING', 'RELEASE', 'ADJUSTMENT', name='cold_store_event_type_enum', native_enum=False), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_kg > 0', name='chk_cold_store_event_quantity_positive'),
    sa.ForeignKeyConstraint(['cold_store_id'], ['cold_stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cold_store_event_query', 'cold_store_events', ['cold_store_id', 'commodity_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_cold_store_events_cold_store_id'), 'cold_store_events', ['cold_store_id'], unique=False)
    op.create_index(op.f('ix_cold_store_events_commodity_id'), 'cold_store_events', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_cold_store_events_id'), 'cold_store_events', ['id'], unique=False)
    op.create_table('cold_store_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cold_store_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('current_quantity_kg', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('current_quantity_kg >= 0', name='chk_cold_store_inventory_non_negative'),
    sa.ForeignKeyConstraint(['cold_store_id'], ['cold_stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cold_store_id', 'commodity_id', name='uq_cold_store_commodity_inventory')
    )
    op.create_index(op.f('ix_cold_store_inventory_cold_store_id'), 'cold_store_inventory', ['cold_store_id'], unique=False)
    op.create_index(op.f('ix_cold_store_inventory_commodity_id'), 'cold_store_inventory', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_cold_store_inventory_id'), 'cold_store_inventory', ['id'], unique=False)
    op.create_table('farmer_supply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('commodity_id', sa.Integer(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_harvest_date', sa.Date(), nullable=False),
    sa.Column('quality_grade', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'READY', 'PARTIALLY_SOLD', 'SOLD', 'STORED', 'CANCELLED', name='supply_status_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('quantity_kg > 0', name='chk_farmer_supply_quantity_positive'),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_farmer_supply_farm_commodity', 'farmer_supply', ['farm_id', 'commodity_id'], unique=False)
    op.create_index('idx_farmer_supply_harvest_commodity', 'farmer_supply', ['commodity_id', 'expected_harvest_date'], unique=False)
    op.create_index(op.f('ix_farmer_supply_commodity_id'), 'farmer_supply', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_farmer_supply_expected_harvest_date'), 'farmer_supply', ['expected_harvest_date'], unique=False)
    op.create_index(op.f('ix_farmer_supply_farm_id'), 'farmer_supply', ['farm_id'], unique=False)
    op.create_index(op.f('ix_farmer_supply_id'), 'farmer_supply', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_farmer_supply_id'), table_name='farmer_supply')
    op.drop_index(op.f('ix_farmer_supply_farm_id'), table_name='farmer_supply')
    op.drop_index(op.f('ix_farmer_supply_expected_harvest_date'), table_name='farmer_supply')
    op.drop_index(op.f('ix_farmer_supply_commodity_id'), table_name='farmer_supply')
    op.drop_index('idx_farmer_supply_harvest_commodity', table_name='farmer_supply')
    op.drop_index('idx_farmer_supply_farm_commodity', table_name='farmer_supply')
    op.drop_table('farmer_supply')
    op.drop_index(op.f('ix_cold_store_inventory_id'), table_name='cold_store_inventory')
    op.drop_index(op.f('ix_cold_store_inventory_commodity_id'), table_name='cold_store_inventory')
    op.drop_index(op.f('ix_cold_store_inventory_cold_store_id'), table_name='cold_store_inventory')
    op.drop_table('cold_store_inventory')
    op.drop_index(op.f('ix_cold_store_events_id'), table_name='cold_store_events')
    op.drop_index(op.f('ix_cold_store_events_commodity_id'), table_name='cold_store_events')
    op.drop_index(op.f('ix_cold_store_events_cold_store_id'), table_name='cold_store_events')
    op.drop_index('idx_cold_store_event_query', table_name='cold_store_events')
    op.drop_table('cold_store_events')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_index(op.f('ix_farms_farmer_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_cold_stores_operator_id'), table_name='cold_stores')
    op.drop_index(op.f('ix_cold_stores_id'), table_name='cold_stores')
    op.drop_index(op.f('ix_cold_stores_district'), table_name='cold_stores')
    op.drop_table('cold_stores')
    op.drop_index(op.f('ix_market_prices_market_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_id'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_date'), table_name='market_prices')
    op.drop_index(op.f('ix_market_prices_commodity_id'), table_name='market_prices')
    op.drop_index('idx_market_price_lookup', table_name='market_prices')
    op.drop_table('market_prices')
    op.drop_index(op.f('ix_market_arrivals_market_id'), table_name='market_arrivals')
    op.drop_index(op.f('ix_market_arrivals_id'), table_name='market_arrivals')
    op.drop_index(op.f('ix_market_arrivals_date'), table_name='market_arrivals')
    op.drop_index(op.f('ix_market_arrivals_commodity_id'), table_name='market_arrivals')
    op.drop_index('idx_market_arrival_lookup', table_name='market_arrivals')
    op.drop_table('market_arrivals')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_index(op.f('ix_farmers_district'), table_name='farmers')
    op.drop_table('farmers')
    op.drop_index(op.f('ix_cold_store_operators_id'), table_name='cold_store_operators')
    op.drop_table('cold_store_operators')
    op.drop_index(op.f('ix_buyer_demand_required_until'), table_name='buyer_demand')
    op.drop_index(op.f('ix_buyer_demand_required_from'), table_name='buyer_demand')
    op.drop_index(op.f('ix_buyer_demand_id'), table_name='buyer_demand')
    op.drop_index(op.f('ix_buyer_demand_commodity_id'), table_name='buyer_demand')
    op.drop_index(op.f('ix_buyer_demand_buyer_id'), table_name='buyer_demand')
    op.drop_index('idx_buyer_demand_commodity_dates', table_name='buyer_demand')
    op.drop_table('buyer_demand')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_identifier'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_district'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_commodities_id'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_code'), table_name='commodities')
    op.drop_table('commodities')
    op.drop_index(op.f('ix_buyers_id'), table_name='buyers')
    op.drop_index(op.f('ix_buyers_district'), table_name='buyers')
    op.drop_table('buyers')
    # ### end Alembic commands ###
